2023-12-05 17:23:07.596 - ETL_FT_SD_TO_XSIFF [ERROR   ] name 'TotalPart' is not defined
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 343, in do_file
    'TotalPart': TotalPart,
NameError: name 'TotalPart' is not defined
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 488, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 392, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2023-12-05 17:23:07.823 - __init__   [ERROR   ] File:TLECGQG81-CW_阳光GD200FYS100L6S.xlsx Move To Error Folder
                                                Error: None
2023-12-05 17:23:08.330 - ETL_FT_SD_TO_XSIFF [ERROR   ] name 'TotalPart' is not defined
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 343, in do_file
    'TotalPart': TotalPart,
NameError: name 'TotalPart' is not defined
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 488, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 392, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2023-12-05 17:23:08.596 - __init__   [ERROR   ] File:XWECYQH20-CW_GD600MLS100L6S.xlsx Move To Error Folder
                                                Error: None
2023-12-05 17:23:09.095 - ETL_FT_SD_TO_XSIFF [ERROR   ] name 'TotalPart' is not defined
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 343, in do_file
    'TotalPart': TotalPart,
NameError: name 'TotalPart' is not defined
Stack (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 488, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 392, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2023-12-05 17:23:09.330 - __init__   [ERROR   ] File:XWECYQH62-GW_GD600MLS100L6S-GW.xlsx Move To Error Folder
                                                Error: None
2023-12-05 17:24:25.291 - ETL_FT_SD_TO_XSIFF [ERROR   ] [Serial no.] This column is numeric only.
2023-12-05 17:24:25.524 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S.xlsx Move To Error Folder
                                                Error: None
2023-12-05 17:32:19.695 - ETL_FT_SD_TO_XSIFF [ERROR   ] name 'bad_part_id' is not defined
Traceback (most recent call last):
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 216, in do_file
    if bad_part_id not in bad_part_ids:
NameError: name 'bad_part_id' is not defined
Stack (most recent call last):
  File "D:\soft\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 2181, in <module>
    main()
  File "D:\soft\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 2172, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\soft\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1484, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "D:\soft\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\soft\PyCharm Community Edition 2022.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 492, in <module>
    skip_file, None, log, config, config_sql)
  File "../..\XdmLib\CustomFuction.py", line 597, in file2db_init
    file, pre_params, db_src, db_tgt)
  File "D:/Ina/ETL_XdmLib_2.A.13/ETL_XdmLib_2.A.13/EDAETL/ETL_TABLE/ETL_FT_SD_TO_XSIFF/ETL_FT_SD_TO_XSIFF.py", line 317, in do_file
    log.error(ex, exc_info=True, stack_info=True)
2023-12-05 17:32:19.943 - __init__   [ERROR   ] File:TLECGQG81-CW_阳光GD200FYS100L6S.xlsx Move To Error Folder
                                                Error: None
2023-12-05 17:54:30.423 - ETL_FT_SD_TO_XSIFF [ERROR   ] [Serial no.] This column is numeric only.
2023-12-05 17:54:30.583 - __init__   [ERROR   ] File:QG35-CW_GD400TAS100L6S.xlsx Move To Error Folder
                                                Error: None
